# Generated by Django 3.1.7 on 2021-03-29 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driverseducation',
            name='modified_date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='medicalprovider',
            name='modified_date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='medicaltype',
            name='modified_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
